from collections import namedtuple

Genotype = namedtuple('Genotype', 'normal normal_concat reduce reduce_concat')


PRIMITIVES_OnlyConv = [
    'k3_e1' ,
    'k3_e1_g2' ,
    'k3_e3' ,
    'k3_e6' ,
    'k5_e1' ,
    'k5_e1_g2',
    'k5_e3',
    'k5_e6',
    'skip',
]

PRIMITIVES_OnlyShiftAdd = [
    'shiftadd_k3_e1' ,
    'shiftadd_k3_e1_g2' ,
    'shiftadd_k3_e3' ,
    'shiftadd_k3_e6' ,
    'shiftadd_k5_e1' ,
    'shiftadd_k5_e1_g2',
    'shiftadd_k5_e3',
    'shiftadd_k5_e6',
    'skip',
]

PRIMITIVES_AddAdd = [
    'k3_e1',
    # 'k3_e1_g2',
    'k3_e3' ,
    'k3_e6' ,
    'k5_e1' ,
    # 'k5_e1_g2',
    'k5_e3',
    'k5_e6',
    'add_k3_e1' ,
    # 'add_k3_e1_g2' ,
    'add_k3_e3' ,
    'add_k3_e6' ,
    'add_k5_e1' ,
    # 'add_k5_e1_g2',
    'add_k5_e3',
    'add_k5_e6',
    'skip',
]

PRIMITIVES_AddShift = [
    'k3_e1' ,
    # 'k3_e1_g2' ,
    'k3_e3' ,
    'k3_e6' ,
    'k5_e1' ,
    # 'k5_e1_g2',
    'k5_e3',
    'k5_e6',
    'shift_k3_e1' ,
    # 'shift_k3_e1_g2' ,
    'shift_k3_e3' ,
    'shift_k3_e6' ,
    'shift_k5_e1' ,
    # 'shift_k5_e1_g2',
    'shift_k5_e3',
    'shift_k5_e6',
    'skip',
]

PRIMITIVES_AddShiftAdd = [
    'k3_e1' ,
    # 'k3_e1_g2' ,
    'k3_e3' ,
    'k3_e6' ,
    'k5_e1' ,
    # 'k5_e1_g2',
    'k5_e3',
    'k5_e6',
    'shiftadd_k3_e1' ,
    # 'shiftadd_k3_e1_g2' ,
    'shiftadd_k3_e3' ,
    'shiftadd_k3_e6' ,
    'shiftadd_k5_e1' ,
    # 'shiftadd_k5_e1_g2',
    'shiftadd_k5_e3',
    'shiftadd_k5_e6',
    'skip',
]

PRIMITIVES_AddAll = [
    'k3_e1' ,
    # 'k3_e1_g2' ,
    'k3_e3' ,
    'k3_e6' ,
    'k5_e1' ,
    # 'k5_e1_g2',
    'k5_e3',
    'k5_e6',
    'add_k3_e1' ,
    # 'add_k3_e1_g2',
    'add_k3_e3' ,
    'add_k3_e6' ,
    'add_k5_e1' ,
    # 'add_k5_e1_g2',
    'add_k5_e3',
    'add_k5_e6',
    'shift_k3_e1' ,
    # 'shift_k3_e1_g2' ,
    'shift_k3_e3' ,
    'shift_k3_e6' ,
    'shift_k5_e1' ,
    # 'shift_k5_e1_g2',
    'shift_k5_e3',
    'shift_k5_e6',
    # 'shiftadd_k3_e1' ,
    # # # 'shiftadd_k3_e1_g2' ,
    # 'shiftadd_k3_e3' ,
    # 'shiftadd_k3_e6' ,
    # 'shiftadd_k5_e1' ,
    # # # 'shiftadd_k5_e1_g2',
    # 'shiftadd_k5_e3',
    # 'shiftadd_k5_e6',
    'skip',
]

PRIMITIVES_NoConv = [
    'skip',
    # 'add_k3_e1' ,
    # 'add_k3_e1_g2' ,
    # 'add_k3_e3' ,
    # 'add_k3_e6' ,
    # 'add_k5_e1' ,
    # 'add_k5_e1_g2',
    # 'add_k5_e3',
    # 'add_k5_e6',
    'shift_k3_e1' ,
    'shift_k3_e1_g2' ,
    'shift_k3_e3' ,
    'shift_k3_e6' ,
    'shift_k5_e1' ,
    'shift_k5_e1_g2',
    'shift_k5_e3',
    'shift_k5_e6',
    'shiftadd_k3_e1' ,
    'shiftadd_k3_e1_g2' ,
    'shiftadd_k3_e3' ,
    'shiftadd_k3_e6' ,
    'shiftadd_k5_e1' ,
    'shiftadd_k5_e1_g2',
    'shiftadd_k5_e3',
    'shiftadd_k5_e6',
]
